name: diabetes
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - asgiref==3.5.2
      - django==4.0.5
      - sqlparse==0.2.4
      - tzdata==2022.1
      - autopep8==1.6.0
      - pycodestyle==2.8.0
      - toml==0.10.2
      - python-decouple==3.6
      - djongo==1.3.6
      - django-extensions==3.1.5
      - django-jazzmin==2.5.0
